{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.name }}-secrets
  labels:
    app: {{ .Values.backend.name }}
    component: backend
    chart: {{ include "chart.name" . }}
    version: {{ include "chart.version" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.appSecrets.data.JWT_SECRET | b64enc }}
  API_KEY: {{ .Values.secrets.appSecrets.data.API_KEY | b64enc }}
{{- end }}
