apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.elasticstack.elasticsearch.serviceName }}-headless
  labels:
    app: {{ .Release.Name }}-elasticsearch
spec:
  clusterIP: None
  ports:
    - port: 9300
      name: transport
  selector:
    app: {{ .Release.Name }}-elasticsearch
