apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-{{ .Values.elasticstack.elasticsearch.serviceName }}
  labels:
    app: {{ .Release.Name }}-elasticsearch
spec:
  serviceName: "{{ .Values.elasticstack.elasticsearch.serviceName }}-headless"
  replicas: {{ .Values.elasticstack.elasticsearch.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-elasticsearch
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: "{{ .Values.elasticstack.elasticsearch.image }}"
          env:
            - name: "discovery.type"
              value: "single-node"
            - name: "ES_JAVA_OPTS"
              value: "-Xms{{ .Values.elasticstack.elasticsearch.heapSize }} -Xmx{{ .Values.elasticstack.elasticsearch.heapSize }}"
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          resources:
{{ toYaml .Values.elasticstack.elasticsearch.resources | indent 12 }}
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
    - metadata:
        name: es-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.elasticstack.elasticsearch.storage }}
