apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-fluentbit
  labels:
    app: {{ .Release.Name }}-fluentbit
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fluentbit
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fluentbit
    spec:
      serviceAccountName: {{ .Release.Name }}-fluentbit
      tolerations: {{ toYaml .Values.elasticstack.fluentbit.tolerations | default "[]" | indent 8 }}
      containers:
        - name: fluentbit
          image: "{{ .Values.elasticstack.fluentbit.image }}"
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: config
              mountPath: /fluent-bit/etc/
          resources:
{{ toYaml .Values.elasticstack.fluentbit.resources | indent 12 }}
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: config
          configMap:
            name: {{ .Release.Name }}-fluentbit-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-fluentbit
  labels:
    app: {{ .Release.Name }}-fluentbit
