{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  labels:
    app: postgresql
    component: database
    chart: {{ include "chart.name" . }}
    version: {{ include "chart.version" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | b64enc }}
  postgres-user: {{ "postgres" | b64enc }}
  postgres-db: {{ .Values.postgresql.auth.database | b64enc }}
{{- end }}

