{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.app.name }}-role
  labels:
    app: {{ .Values.app.name }}
    chart: {{ include "chart.name" . }}
    version: {{ include "chart.version" . }}
    release: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/status", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors", "prometheusrules"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.app.name }}-rolebinding
  labels:
    app: {{ .Values.app.name }}
    chart: {{ include "chart.name" . }}
    version: {{ include "chart.version" . }}
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.app.name }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "serviceAccount.name" . }}
  namespace: {{ .Release.Namespace }}
---
# ClusterRole for monitoring and metrics
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.app.name }}-cluster-role
  labels:
    app: {{ .Values.app.name }}
    chart: {{ include "chart.name" . }}
    version: {{ include "chart.version" . }}
    release: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/metrics", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors", "prometheusrules", "alertmanagers", "prometheuses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.app.name }}-cluster-rolebinding
  labels:
    app: {{ .Values.app.name }}
    chart: {{ include "chart.name" . }}
    version: {{ include "chart.version" . }}
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.app.name }}-cluster-role
subjects:
- kind: ServiceAccount
  name: {{ include "serviceAccount.name" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
