{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secrets
  labels:
    app: {{ .Values.app.name }}
    chart: {{ include "chart.name" . }}
    version: {{ include "chart.version" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.appSecrets.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
# Database secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-db-secrets
  labels:
    app: {{ .Values.app.name }}
    chart: {{ include "chart.name" . }}
    version: {{ include "chart.version" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  postgres-password: {{ "postgres" | b64enc }}
  postgres-user: {{ "postgres" | b64enc }}
  postgres-db: {{ "appdb" | b64enc }}
---
# Cache secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-cache-secrets
  labels:
    app: {{ .Values.app.name }}
    chart: {{ include "chart.name" . }}
    version: {{ include "chart.version" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  redis-password: {{ "" | b64enc }}
---
# Message queue secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-queue-secrets
  labels:
    app: {{ .Values.app.name }}
    chart: {{ include "chart.name" . }}
    version: {{ include "chart.version" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  rabbitmq-user: {{ "user" | b64enc }}
  rabbitmq-password: {{ "password" | b64enc }}
  rabbitmq-vhost: {{ "/" | b64enc }}
---
# Monitoring secrets
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-basic-auth
  labels:
    app: {{ .Values.app.name }}
    chart: {{ include "chart.name" . }}
    version: {{ include "chart.version" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  auth: {{ "admin:$2y$10$8K1p/a0dL2Lz0bVQvmV2Ceuj1nNe8p5aW0zb9uI4buUxtO9bXo3u2" | b64enc }}
{{- end }}
